version: "3"
services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    image: backend-local-prod:production-v7 #Update version number
    env_file: 
      - ./.env.local # file with BACKEND_BASE_URL

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: dockerfile
      args:
        - NODE_ENV=prod
    ports:
      - "80:3000"
    depends_on:
      - backend
    image: frontend-local:production-v10  #Update version number
    env_file: 
      - ./packages/frontend/.env.prod.frontend
  
#Buld and run
# E
# docker-compose -f docker-compose.prod.yml down
# docker-compose -f docker-compose.prod.yml build
# docker-compose -f docker-compose.prod.yml logs

# docker-compose -f docker-compose.prod.yml build --build-arg NODE_ENV=prod
