version: "3"
services:
  backend:
    build:
      context: ./packages/backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./packages/frontend
    ports:
        - "3000:3000"
    depends_on:
        - backend



#Buld and run
# docker-compose up
#docker-compose down