version: "3"
services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    # volumes:
    #   - ./packages/backend:/app
    ports:
      - "5000:5000"
    image: backend-local:production-v4
    # environment:
    #   - BACKEND_BASE_URL=${BACKEND_BASE_URL}
    env_file: 
      - .env.local

  frontend:
    build:
      context: ./packages/frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    image: frontend-local:production-v4
    # environment:
    #   - REACT_APP_BACKEND_BASE_URL=${REACT_APP_BACKEND_BASE_URL}
    
    env_file: 
      - ./packages/frontend/.env.prod
  
#Buld and run
# docker-compose up
#docker-compose down
