version: "3"
services:
  backend:
    build:
      context: ./packages/backend
    ports:
      - "5000:5000"
    # depends_on:
    #   - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}

  frontend:
    build:
      context: ./packages/frontend
    ports:
        - "3000:3000"
    depends_on:
        - backend

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #       - "27017:27017"

#Buld and run
# docker-compose up
#docker-compose down