version: "3"
services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    volumes: 
      - ./packages/backend:/app
    ports:
      - "5000:5000"
    image: 460003776558.dkr.ecr.us-east-1.amazonaws.com/plantainapp


  frontend:
    build:
      context: ./packages/frontend
    ports:
        - "3000:3000"
    depends_on:
        - backend
    image: 460003776558.dkr.ecr.us-east-1.amazonaws.com/frontend



#Buld and run
# docker-compose up
#docker-compose down