version: "3"
services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    volumes:
      - ./packages/backend:/app
    ports:
      - "5000:5000"
    image: backend-dev-env:development-v1  #Update version number
    environment:
      - BACKEND_BASE_URL=${BACKEND_BASE_URL:-http://localhost}
    # env_file:
    #   - .env.local

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: ./packages/frontend/dockerfile

    ports:
      - "3000:3000"
    depends_on:
      - backend
    image: frontend-dev-env:development-v2 #Update version number
    # environment:
    #   - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    env_file:
      - ./packages/frontend/.env.local.frontend
    volumes:
      - ./packages/backend:/app

#Buld and run
# docker-compose up -d
#docker-compose down
