name: Build and Deploy Backend

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    #run workflow in the latest version of Ubuntu
    runs-on: ubuntu-latest

    #Adding Continuous Integration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Backend Dependencies
        run: |
          cd packages/backend/
          npm install

      - name: Run Jest Test Backend
        run: |
          cd packages/backend/
          npm test

      - name: Build Docker Image
        run: |
          cd packages/backend/
          docker build -t 460003776558.dkr.ecr.us-east-1.amazonaws.com/plantainapp:latest .

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 460003776558.dkr.ecr.us-east-1.amazonaws.com/plantainapp
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    
      - name: Push Docker Image
        run: |
          docker push f460003776558.dkr.ecr.us-east-1.amazonaws.com/plantainapp:latest
          
          
